travis:
  secure:
    BINSTAR_TOKEN: oZEjjh/Ca+QBURTGoCpsLQrYHB/316DffoFCn78CkdjuMDfxwG99BNI3MLoGe9vO3D/8r43VQsHGO+yMAuy+BIsqbN9UrVkZ6MepHOx7MOniR3C9HPR1AgFRyGszJRBMRW8WgJLS/Mf3gIAMdbJEL/1iY1BslrB7bXCBjy1u27Z5pVz/MD7n1bwgKtzxTNYzb3StmFo5Pbaf2/Uhl2ivrOaZv4a6W1pnpcIe9LfR518ttYoGcJuql/jH6weqKk/tDgi+OghTdtqZitkZPmBJ1pv1GtvLgdkEhyVphCR2kRsVbppgyVfXmQAYU0LhYNRyNV6i+brxPMh4QRKp6xRjE6ZFcg1KzO0ha5tIoWkrEcnWHFmE8NesTRYtojLoKmjITQAswr3z3Eid70MZy1Bwbu3tGU62IZCQudA8bfYzNxo24kc/KGKe29tPCkI1ZzPZ025yfywAF14fnRbw4IIsM2/J901PvgxPiu1ZG2ekIwYrIp0EuhzMj4AV7uIpmDMX8YpFPoNql9VEKK1iZGWdt6aAEw+ZoY5fXnVI8yqEmBdl6c5+Z7RRAPBAYVD8dMG5wkdibcvF+yGhTqQvEHB/RK8KEtwkF1qEIVNH7CTnCWzn16yyFiiveV6vcdp8uBZ/Uv1kgBrXWLqtFsbZP4fUh2hBzbvjxgBRPSNkgktXJ6o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
